# Generated by Django 6.1 on 2026-08-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
