# Generated by Django 6.1 on 2026-08-18 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
