# Generated by Django 6.1 on 2026-08-18 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_estudiante_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
